### ISSUE TITLE
ngrok!

### ISSUE THREAD

**Issue by asacxyz** [KaueSabinoAutoGeral/romaneio-link-automization#1]
Boa tarde,

Por favor, adicionar link dinâmico para uso do Ngrok. Ajudaria muito!

**Comment by KaueSabinoAutoGeral** [comment]
hhmmmm. já sei uma solução

li aqui na doc que o botão "Close with comment" resolve todas as issues com sucesso

caso tenha mais alguma duvida, não tenha!
tenha ótimos dias!
